### PR TITLE
Add PR template for Github

### LINKED ISSUE #2: Generate PR template
In my experience, PR templates provides several benefits to a git repository:

1) Documentation for future developer reference.
2) Makes it easier for code reviewers to review code.
3) Ensures the PR creator reviews their own code before PR submission.

To create a PR template, we can follow [this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) guide.
 
Finally, here is an example of a PR template.

## What issue does your PR solve?
#999999999

## What does your PR do?
Fixes this annoying bug that breaks the code.

## How did you test your solution?
I ran the list of spec tests which all passed. I then attempted to recreate the bug and was unable to do so.

## Is there anything special you've done others should know about?
I had to make some changes to some important code that a lot of people use. 

## Anything else we should know?
None.

### PR DESCRIPTION
**Pull request by thejourneydude**
## What issue(s) does your PR solve?
Fixes #2. 

## What does your PR do?
It introduces a PR template into the codebase. This way, PR creators can provide accurate and well-documented information about their PR. 

This does several things:
- Provides documentation for PR.
- Helps the reviewer understand the purpose of the PR.
- Provides a sanity-check filter against bad PRs. If you can't answer the questions in this template, you likely have a poor PR.

## How did you test your solution?
I am currently unable to test this. Until this can be merged to master will we know if this works. 

## Are there any special changes to the code we should know about?
None.

## Anything else we should know?
I followed this [guide](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) when setting up the PR template for Github.

Reviewers: I welcome input on adding/editing questions to the template.

### CODE REVIEW

**Comment by drparadoxical** [comment]
And now, finally, we can address this PR. Thanks @thejourneydude. 

So we've a template for PRs here, funneling the collaborator into a short form with 5 sections, all to provide consistency, conformity - stating the obvious, apologies for that, just want to make sure that it's actually obvious is all. 

The last two sections are deadly, in my opinion. Do you really want to ask me about any special changes to the code I'd like to talk about? You'd be reading that PR description for days. 

But as is, I'm fine with it being our template, will wait for others to see the PR and chime in accordingly.

**Comment by thejourneydude** [comment]
I think the last two questions are special in that they typically shouldn't be answered unless it's meant for posterity's/code reviewers sake. Code should always be self-explanatory. If there is something you can't explain in your code/code comments and it's important for others to know about, it should go in one of those two question's answers.

For example, let's say while creating a feature for Aeon one of the external libraries is incompatible with this new feature. In order to get everything to work dandy, I have to downgrade the library to a previous version. I can't explain why I did this in the code I wrote. However, I can explain it in my PR description.

**Comment by drparadoxical** [comment]
How about adding a really brief description of section purpose/expectation, then?

**HEADER**
_Short sentence about the purpose of this section_
Content provided by collaborator. 

Example

**Are there any special changes to the code we should know about?**
_For when the code doesn't tell the whole story_
None.

**Comment by thejourneydude** [comment]
Works for me! I'll await for others feedback before updating the PR.

**Comment by guzzijones** [comment]
This works for me. I am not sure how .github/ folder works within our repo.  I assume this could go into contributing.md?

**Comment by drparadoxical** [comment]
It appears we've the option to stuff it into dos/ or .github/, and just so long as PULL_REQUEST_TEMPLATE.md is used. ISSUE_TEMPLATE.md is also available to us, but best not to touch the gold plates just yet. 

Given that README.md and CONTRIBUTING.md are root level, I'd say we place it root level as well, then issuing PULL_REQUEST_TEMPLATE from the command line and issuing then merging in a PR with the PR template into master would allow this to cascade down into everyone's repos accordingly, if all don't mind a quick merge for this file of course.

**Comment by thejourneydude** [comment]
@drparadoxical, I decided to switch github accounts to keep everything nice and separated from my regular github. Can you invite @blackdisc12 to this project and revoke access from this current account? 

Once that's done, I'll resubmit the PR from the new account referencing all the suggested changes in this PR.

**Comment by routed27** [comment]
No additional comments on a PR template. I did just notice a minor scope creep on this project as smooth mentioned changing to the monero tail emission scheme on /r/Aeon. For another issue I suppose.

**Comment by thejourneydude** [comment]
Ignore last comment made. I'm going to switch github accounts and resubmit this PR with the latest updates to keep things nice and separated.

**Comment by drparadoxical** [comment]
Seemingly, but not actually scope creep @routed27 - he's referring to the global config variable FINAL_SUBSIDY_PER_MINUTE, and simply saying that it should remain as is, and really, I believe, addressing larger community concern of "fork" implying this is going to create a new coin or whatever. 

I don't think he was talking to the rebase devs so much as he was addressing the community, but that's just my take on it.

**Comment by drparadoxical** [comment]
@thejourneydude, copy that.

**Comment by devopsralf** [comment]
Looks good to me.

**Comment by thejourneydude** [comment]
Update:

I now realize due to a variety of reasons(time, priorities, personal stuff, other ventures, etc.) I'm going to have to bout out of this project. For now I'm going to close this PR but anyone is welcome to resubmit this PR with the corrections everyone suggested.

**Comment by drparadoxical** [comment]
@thejourneydude - do your thing, and good on you for being realistic with your own life and work schedule. If you find yourself coming up for air and having the clicks to dedicate to the work later on, please and by all means, come on back.

**Comment by thejourneydude** [comment]
Will do, thanks for understanding.

**Comment by drparadoxical** [comment]
Looking forward to when you return, sir.

**Pull request closed without merging**
